import { RECEIVED_ITEM_FROM_B, TALKED_TO_A, TALKED_TO_B } from '../constants/storyFlags';
import type { LevelMap } from '../lib/LevelBuilder/levelBuilder.types';

export const TILESET_LEVEL: LevelMap = {
  id: 'tilesetLevel',
  heroDefaultPosition: {
    x: 1,
    y: 5,
  },
  gameObjects: [
    {
      type: 'Exit',
      id: 'exitGrass1',
      newLevelId: 'tilesetLevel',
      x: 1,
      y: 4,
      heroNewPosition: {
        x: 6,
        y: 4,
      },
    },
    {
      type: 'Chest',
      id: 'chest1',
      interactionConfig: {
        content: [
          {
            string: [],
            item: 'hammer1',
          },
        ],
      },
      x: 2,
      y: 0,
    },
    {
      type: 'Chest',
      id: 'chest2',
      interactionConfig: {
        content: [
          {
            string: ['You found an hammer'],
            item: 'hammer1',
          },
        ],
      },
      x: 4,
      y: 0,
    },
    {
      type: 'Chest',
      id: 'chest3',
      interactionConfig: {
        content: [
          {
            string: ['You found a rod'],
            item: 'rod1',
          },
        ],
      },
      x: 6,
      y: 0,
    },
    {
      type: 'Chest',
      id: 'chest3',
      interactionConfig: {
        content: [
          {
            string: ['You found a slingshot!'],
            requires: [TALKED_TO_B],
            item: 'slingshot1',
          },
          {
            string: ['I have to talk with B first...'],
          },
        ],
      },
      x: 8,
      y: 0,
    },
    {
      type: 'Chest',
      id: 'chest5',
      interactionConfig: {
        content: [
          {
            string: [],
            item: 'potion2',
          },
        ],
      },
      removeAfterLoot: true,
      x: 10,
      y: 0,
    },
    {
      type: 'CollectibleItem',
      id: 'rod',
      item: 'rod2',
      x: 7,
      y: 5,
    },
    {
      type: 'CollectibleItem',
      id: 'heart',
      item: 'heart',
      x: 10,
      y: 3,
      shouldSkipPickupAnimation: true,
    },
    {
      type: 'Decoration',
      id: 'rock1-decoration',
      key: 'rock1BaseGrass',
      x: 7,
      y: 0,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'rock2-decoration',
      key: 'rock1BaseGrass',
      x: 10,
      y: 1,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'rock3-decoration',
      key: 'rock1BaseGrass',
      x: 11,
      y: 1,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'rock4-decoration',
      key: 'rock1BaseGrass',
      x: 11,
      y: 2,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'rock5-decoration',
      key: 'rock1BaseGrass',
      x: 1,
      y: 3,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'rockGrass-decoration',
      key: 'rock2BaseGrass',
      x: 2,
      y: 3,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'rockGrass1-decoration',
      key: 'rock2BaseGrass',
      x: 2,
      y: 4,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'rock6-decoration',
      key: 'rock1BaseGrass',
      x: 1,
      y: 3,
      isSolid: true,
    },
    {
      type: 'Npc',
      id: 'npc1',
      x: 6,
      y: 3,
      npc: 'ow1',
      interactionConfig: {
        content: [
          {
            string: ["I just can't stand that guy."],
            requires: [TALKED_TO_B],
            bypass: [TALKED_TO_A],
            addsFlag: TALKED_TO_A,
          },
          {
            string: ['He is just the worst!'],
            requires: [TALKED_TO_A],
          },
          {
            string: ['Grumble grumble. Another day at work'],
          },
        ],
        portraitFrame: 1,
      },
      behaviorConfig: [
        { type: 'walk', direction: 'DOWN' },
        { type: 'stand', direction: 'LEFT', duration: 1200 },
        { type: 'walk', direction: 'RIGHT' },
        { type: 'stand', direction: 'DOWN', duration: 1200 },
        { type: 'walk', direction: 'UP' },
        { type: 'stand', direction: 'RIGHT', duration: 1200 },
        { type: 'walk', direction: 'LEFT' },
        { type: 'stand', direction: 'UP', duration: 1200 },
      ],
    },
    {
      type: 'Npc',
      id: 'npc2',
      x: 9,
      y: 4,
      npc: 'ow2',
      interactionConfig: {
        content: [
          {
            string: ["Oh, here's your item"],
            requires: [TALKED_TO_B],
            bypass: [RECEIVED_ITEM_FROM_B],
            addsFlag: RECEIVED_ITEM_FROM_B,
            item: 'hammer1',
          },
          {
            string: ['Now you are more powerful!'],
            requires: [RECEIVED_ITEM_FROM_B],
          },
          {
            string: ['What a beautiful day to work in the cave!'],
            bypass: [TALKED_TO_B],
            addsFlag: TALKED_TO_B,
          },
        ],
        portraitFrame: 0,
      },
      behaviorConfig: [
        { type: 'stand', direction: 'DOWN', duration: 1000 },
        { type: 'stand', direction: 'LEFT', duration: 1000 },
        { type: 'stand', direction: 'UP', duration: 1000 },
        { type: 'stand', direction: 'RIGHT', duration: 1000 },
      ],
    },
    {
      type: 'Npc',
      id: 'npc3',
      x: 14,
      y: 6,
      npc: 'ow3',
      interactionConfig: {
        content: [
          {
            string: ['Go away!', "You're not welcomed here!"],
          },
        ],
        portraitFrame: 0,
      },
    },
    {
      type: 'Npc',
      id: 'npc4',
      x: 1,
      y: 0,
      npc: 'ow4',
      interactionConfig: {
        content: [{ string: ['Hi there!'] }],
      },
      behaviorConfig: [
        { type: 'stand', direction: 'UP', duration: 800 },
        { type: 'stand', direction: 'RIGHT', duration: 800 },
        { type: 'stand', direction: 'DOWN', duration: 1200 },
      ],
    },
  ],
  walls: [
    // Upper walls
    '0,-1',
    '1,-1',
    '2,-1',
    '3,-1',
    '4,-1',
    '5,-1',
    '6,-1',
    '7,-1',
    '8,-1',
    '9,-1',
    '10,-1',
    '11,-1',
    '12,-1',
    '13,-1',
    '14,-1',
    '15,-1',

    // Left walls
    '0,0',
    '0,1',
    '0,2',
    '0,3',
    '0,4',
    '0,5',
    '0,6',
    '0,7',
    '0,8',

    // Right walls
    '15,0',
    '15,1',
    '15,2',
    '15,3',
    '15,4',
    '15,5',
    '15,6',
    '15,7',
    '15,8',

    // Lower walls
    '0,7',
    '1,7',
    '2,7',
    '3,7',
    '4,7',
    '5,7',
    '6,7',
    '7,7',
    '8,7',
    '9,7',
    '10,7',
    '11,7',
    '12,7',
    '13,7',
    '14,7',
    '15,7',
  ],
  tiles: {
    // First row
    '0,0': 'grassCliffBorderUpperLeft',
    '1,0': 'grassCliffBorderUpper',
    '2,0': 'grassCliffBorderUpper',
    '3,0': 'grassCliffBorderUpper',
    '4,0': 'grassCliffBorderUpper',
    '5,0': 'grassCliffBorderUpper',
    '6,0': 'grassCliffBorderUpper',
    '7,0': 'grassCliffBorderUpper',
    '8,0': 'grassCliffBorderUpper',
    '9,0': 'grassCliffBorderUpper',
    '10,0': 'grassCliffBorderUpper',
    '11,0': 'grassCliffBorderUpper',
    '12,0': 'grassCliffBorderUpper',
    '13,0': 'grassCliffBorderUpper',
    '14,0': 'grassCliffBorderUpper',
    '15,0': 'grassCliffBorderUpperRight',
    // Second row
    '0,1': 'grassCliffBorderLeft',
    '1,1': 'grass',
    '2,1': 'grass',
    '3,1': 'grass',
    '4,1': 'grass',
    '5,1': 'grass',
    '6,1': 'grass',
    '7,1': 'grass',
    '8,1': 'grass',
    '9,1': 'grass',
    '10,1': 'grass',
    '11,1': 'grass',
    '12,1': 'grass',
    '13,1': 'grass',
    '14,1': 'grass',
    '15,1': 'grassCliffBorderRight',
    // Third row
    '0,2': 'grassCliffBorderLeft',
    '1,2': 'grass',
    '2,2': 'grass',
    '3,2': 'waterAnimatedGrassLedgeBorderUpperLeft',
    '4,2': 'waterAnimatedGrassLedgeBorderUpper',
    '5,2': 'waterAnimatedGrassLedgeBorderUpperRight',
    '6,2': 'waterGrassLedgeBorderUpperLeft',
    '7,2': 'waterGrassLedgeBorderUpper',
    '8,2': 'waterGrassLedgeBorderUpperRight',
    '9,2': 'grass',
    '10,2': 'grass',
    '11,2': 'grass',
    '12,2': 'grass',
    '13,2': 'grass',
    '14,2': 'grass',
    '15,2': 'grassCliffBorderRight',
    // Fourth row
    '0,3': 'grassCliffBorderLeft',
    '1,3': 'grass',
    '2,3': 'grass',
    '3,3': 'waterAnimatedGrassLedgeBorderLowerLeft',
    '4,3': 'waterAnimatedGrassLedgeBorderLower',
    '5,3': 'waterAnimatedGrassLedgeBorderLowerRight',
    '6,3': 'waterGrassLedgeBorderLowerLeft',
    '7,3': 'waterGrassLedgeBorderLower',
    '8,3': 'waterGrassLedgeBorderLowerRight',
    '9,3': 'grass',
    '10,3': 'grass',
    '11,3': 'grass',
    '12,3': 'grass',
    '13,3': 'grass',
    '14,3': 'grass',
    '15,3': 'grassCliffBorderRight',
    // Fifth row
    '0,4': 'grassCliffBorderLeft',
    '1,4': 'grass',
    '2,4': 'grass',
    '3,4': 'grass',
    '4,4': 'grass',
    '5,4': 'grass',
    '6,4': 'grass',
    '7,4': 'grass',
    '8,4': 'grass',
    '9,4': 'grass',
    '10,4': 'grass',
    '11,4': 'grass',
    '12,4': 'grass',
    '13,4': 'grass',
    '14,4': 'grass',
    '15,4': 'grassCliffBorderRight',
    // Sixth row
    '0,5': 'grassCliffBorderLeft',
    '1,5': 'grass',
    '2,5': 'grass',
    '3,5': 'grass',
    '4,5': 'grass',
    '5,5': 'grass',
    '6,5': 'grass',
    '7,5': 'grass',
    '8,5': 'grass',
    '9,5': 'grass',
    '10,5': 'grass',
    '11,5': 'grass',
    '12,5': 'grass',
    '13,5': 'grass',
    '14,5': 'grass',
    '15,5': 'grassCliffBorderRight',
    // Seventh row
    '0,6': 'grassCliffBorderLeft',
    '1,6': 'grass',
    '2,6': 'grass',
    '3,6': 'grass',
    '4,6': 'grass',
    '5,6': 'grass',
    '6,6': 'grass',
    '7,6': 'grass',
    '8,6': 'grass',
    '9,6': 'grass',
    '10,6': 'grass',
    '11,6': 'grass',
    '12,6': 'grass',
    '13,6': 'grass',
    '14,6': 'grass',
    '15,6': 'grassCliffBorderRight',
    // Eighth row
    '0,7': 'grassCliffBorderLowerLeft',
    '1,7': 'grassCliffBorderLower',
    '2,7': 'grassCliffBorderLower',
    '3,7': 'grassCliffBorderLower',
    '4,7': 'grassCliffBorderLower',
    '5,7': 'grassCliffBorderLower',
    '6,7': 'grassCliffBorderLower',
    '7,7': 'grassCliffBorderLower',
    '8,7': 'grassCliffBorderLower',
    '9,7': 'grassCliffBorderLower',
    '10,7': 'grassCliffBorderLower',
    '11,7': 'grassCliffBorderLower',
    '12,7': 'grassCliffBorderLower',
    '13,7': 'grassCliffBorderLower',
    '14,7': 'grassCliffBorderLower',
    '15,7': 'grassCliffBorderLowerRight',
  },
};
