import type { TilesetFrameMap } from './tileset.types';

export const TILESET_FRAME_MAP: TilesetFrameMap = {
  // Grass
  grass: 0,

  // Sand
  sand: 1,

  // Snow
  snow: 2,

  // Bushes
  bushBgGrass: 3,
  bushBgSand: 4,
  bushBgSnow: 5,
  bushBgTransparent: 6,

  // Water animations
  water1: 7,
  water2: 8,
  water3: 9,
  water4: 10,

  // Ice
  ice: 11,

  // Rocks
  rock1BaseGrass: 12,
  rock2BaseGrass: 13,
  rock1BaseSand: 14,
  rock2BaseSand: 15,
  rock1BaseSnow: 16,
  rock2BaseSnow: 17,

  // Sand with grass border
  sandGrassBorderUpperLeft: 52,
  sandGrassBorderUpper: 53,
  sandGrassBorderUpperRight: 54,
  sandGrassBorderLeft: 104,
  sandGrassBorderRight: 106,
  sandGrassBorderLowerLeft: 156,
  sandGrassBorderLower: 157,
  sandGrassBorderLowerRight: 158,

  // Grass with sand border
  grassSandBorderUpperLeft: 55,
  grassSandBorderUpper: 56,
  grassSandBorderUpperRight: 57,
  grassSandBorderLeft: 107,
  grassSandBorderRight: 109,
  grassSandBorderLowerLeft: 159,
  grassSandBorderLower: 160,
  grassSandBorderLowerRight: 161,

  // Grass with cliff border
  grassCliffBorderUpperLeft: 58,
  grassCliffBorderUpper: 59,
  grassCliffBorderUpperRight: 60,
  grassCliffBorderLeft: 110,
  grassCliffBorderRight: 112,
  grassCliffBorderLowerLeft: 162,
  grassCliffBorderLower: 163,
  grassCliffBorderLowerRight: 164,

  // Cliff with grass border
  cliffGrassBorderUpperLeft: 61,
  cliffGrassBorderUpper: 62,
  cliffGrassBorderUpperRight: 63,
  cliffGrassBorderLeft: 113,
  cliffGrassBorderRight: 115,
  cliffGrassBorderLowerLeft: 165,
  cliffGrassBorderLower: 166,
  cliffGrassBorderLowerRight: 167,

  // Sand with cliff border
  sandCliffBorderUpperLeft: 64,
  sandCliffBorderUpper: 65,
  sandCliffBorderUpperRight: 66,
  sandCliffBorderLeft: 116,
  sandCliffBorderRight: 118,
  sandCliffBorderLowerLeft: 168,
  sandCliffBorderLower: 169,
  sandCliffBorderLowerRight: 170,

  // Cliff with sand border
  cliffSandBorderUpperLeft: 67,
  cliffSandBorderUpper: 68,
  cliffSandBorderUpperRight: 69,
  cliffSandBorderLeft: 119,
  cliffSandBorderRight: 121,
  cliffSandBorderLowerLeft: 171,
  cliffSandBorderLower: 172,
  cliffSandBorderLowerRight: 173,

  // Snow with cliff border
  snowCliffBorderUpperLeft: 70,
  snowCliffBorderUpper: 71,
  snowCliffBorderUpperRight: 72,
  snowCliffBorderLeft: 122,
  snowCliffBorderRight: 124,
  snowCliffBorderLowerLeft: 174,
  snowCliffBorderLower: 175,
  snowCliffBorderLowerRight: 176,

  // Cliff with snow border
  cliffSnowBorderUpperLeft: 73,
  cliffSnowBorderUpper: 74,
  cliffSnowBorderUpperRight: 75,
  cliffSnowBorderLeft: 125,
  cliffSnowBorderRight: 127,
  cliffSnowBorderLowerLeft: 177,
  cliffSnowBorderLower: 178,
  cliffSnowBorderLowerRight: 179,

  // Snow with grass border
  snowGrassBorderUpperLeft: 76,
  snowGrassBorderUpper: 77,
  snowGrassBorderUpperRight: 78,
  snowGrassBorderLeft: 128,
  snowGrassBorderRight: 130,
  snowGrassBorderLowerLeft: 180,
  snowGrassBorderLower: 181,
  snowGrassBorderLowerRight: 182,

  // Grass with snow border
  grassSnowBorderUpperLeft: 79,
  grassSnowBorderUpper: 80,
  grassSnowBorderUpperRight: 81,
  grassSnowBorderLeft: 131,
  grassSnowBorderRight: 133,
  grassSnowBorderLowerLeft: 183,
  grassSnowBorderLower: 184,
  grassSnowBorderLowerRight: 185,

  // Grass with ledge border
  grassLedgeBorderUpperLeft: 208,
  grassLedgeBorderUpper: 209,
  grassLedgeBorderUpperRight: 210,
  grassLedgeBorderLeft: 260,
  grassLedgeBorderRight: 262,
  grassLedgeBorderLowerLeft: 312,
  grassLedgeBorderLower: 313,
  grassLedgeBorderLowerRight: 314,

  // Ledge with grass border
  ledgeGrassBorderUpperLeft: 211,
  ledgeGrassBorderUpper: 212,
  ledgeGrassBorderUpperRight: 213,
  ledgeGrassBorderLeft: 263,
  ledgeGrassBorderRight: 265,
  ledgeGrassBorderLowerLeft: 315,
  ledgeGrassBorderLower: 316,
  ledgeGrassBorderLowerRight: 317,

  // Grass ledges
  ledgeGrassLower1: 214,
  ledgeGrassLower2: 215,
  ledgeGrassUpper1: 266,
  ledgeGrassUpper2: 267,
  ledgeGrassRight1: 216,
  ledgeGrassRight2: 268,
  ledgeGrassLeft1: 217,
  ledgeGrassLeft2: 269,

  // Grass Stairs
  grassStairs2stepsLower: 318,
  grassStairs3stepsLower: 319,
  grassStairs2stepsLeft: 320,
  grassStairs2stepsRight: 321,

  // Sand with ledge border
  sandLedgeBorderUpperLeft: 214,
  sandLedgeBorderUpper: 215,
  sandLedgeBorderUpperRight: 216,
  sandLedgeBorderLeft: 267,
  sandLedgeBorderRight: 269,
  sandLedgeBorderLowerLeft: 318,
  sandLedgeBorderLower: 319,
  sandLedgeBorderLowerRight: 320,

  // Ledge with sand border
  ledgeSandBorderUpperLeft: 217,
  ledgeSandBorderUpper: 218,
  ledgeSandBorderUpperRight: 219,
  ledgeSandBorderLeft: 270,
  ledgeSandBorderRight: 272,
  ledgeSandBorderLowerLeft: 321,
  ledgeSandBorderLower: 322,
  ledgeSandBorderLowerRight: 323,

  // Sand ledges
  ledgeSandLower1: 0,
  ledgeSandLower2: 0,
  ledgeSandUpper1: 0,
  ledgeSandUpper2: 0,
  ledgeSandRight1: 0,
  ledgeSandRight2: 0,
  ledgeSandLeft1: 0,
  ledgeSandLeft2: 0,

  // Sand Stairs
  sandStairs2stepsLower: 0,
  sandStairs3stepsLower: 0,
  sandStairs2stepsLeft: 0,
  sandStairs2stepsRight: 0,

  // Snow with ledge border
  snowLedgeBorderUpperLeft: 0,
  snowLedgeBorderUpper: 0,
  snowLedgeBorderUpperRight: 0,
  snowLedgeBorderLeft: 0,
  snowLedgeBorderRight: 0,
  snowLedgeBorderLowerLeft: 0,
  snowLedgeBorderLower: 0,
  snowLedgeBorderLowerRight: 0,

  // Ledge with snow border
  ledgeSnowBorderUpperLeft: 0,
  ledgeSnowBorderUpper: 0,
  ledgeSnowBorderUpperRight: 0,
  ledgeSnowBorderLeft: 0,
  ledgeSnowBorderRight: 0,
  ledgeSnowBorderLowerLeft: 0,
  ledgeSnowBorderLower: 0,
  ledgeSnowBorderLowerRight: 0,

  // Snow ledges
  ledgeSnowLower1: 0,
  ledgeSnowLower2: 0,
  ledgeSnowUpper1: 0,
  ledgeSnowUpper2: 0,
  ledgeSnowRight1: 0,
  ledgeSnowRight2: 0,
  ledgeSnowLeft1: 0,
  ledgeSnowLeft2: 0,

  // Snow Stairs
  snowStairs2stepsLower: 0,
  snowStairs3stepsLower: 0,
  snowStairs2stepsLeft: 0,
  snowStairs2stepsRight: 0,

  // Water animations with grass ledge border
  water1GrassLedgeBorderUpperLeft: 0,
  water1GrassLedgeBorderUpper: 0,
  water1GrassLedgeBorderUpperRight: 0,
  water1GrassLedgeBorderLeft: 0,
  water1GrassLedgeBorderRight: 0,
  water1GrassLedgeBorderLowerLeft: 0,
  water1GrassLedgeBorderLower: 0,
  water1GrassLedgeBorderLowerRight: 0,
  water2GrassLedgeBorderUpperLeft: 0,
  water2GrassLedgeBorderUpper: 0,
  water2GrassLedgeBorderUpperRight: 0,
  water2GrassLedgeBorderLeft: 0,
  water2GrassLedgeBorderRight: 0,
  water2GrassLedgeBorderLowerLeft: 0,
  water2GrassLedgeBorderLower: 0,
  water2GrassLedgeBorderLowerRight: 0,
  water3GrassLedgeBorderUpperLeft: 0,
  water3GrassLedgeBorderUpper: 0,
  water3GrassLedgeBorderUpperRight: 0,
  water3GrassLedgeBorderLeft: 0,
  water3GrassLedgeBorderRight: 0,
  water3GrassLedgeBorderLowerLeft: 0,
  water3GrassLedgeBorderLower: 0,
  water3GrassLedgeBorderLowerRight: 0,
  water4GrassLedgeBorderUpperLeft: 0,
  water4GrassLedgeBorderUpper: 0,
  water4GrassLedgeBorderUpperRight: 0,
  water4GrassLedgeBorderLeft: 0,
  water4GrassLedgeBorderRight: 0,
  water4GrassLedgeBorderLowerLeft: 0,
  water4GrassLedgeBorderLower: 0,
  water4GrassLedgeBorderLowerRight: 0,

  // Grass ledge with water animations border
  grassLedgeWater1BorderUpperLeft: 0,
  grassLedgeWater1BorderUpper: 0,
  grassLedgeWater1BorderUpperRight: 0,
  grassLedgeWater1BorderLeft: 0,
  grassLedgeWater1BorderRight: 0,
  grassLedgeWater1BorderLowerLeft: 0,
  grassLedgeWater1BorderLower: 0,
  grassLedgeWater1BorderLowerRight: 0,
  grassLedgeWater2BorderUpperLeft: 0,
  grassLedgeWater2BorderUpper: 0,
  grassLedgeWater2BorderUpperRight: 0,
  grassLedgeWater2BorderLeft: 0,
  grassLedgeWater2BorderRight: 0,
  grassLedgeWater2BorderLowerLeft: 0,
  grassLedgeWater2BorderLower: 0,
  grassLedgeWater2BorderLowerRight: 0,
  grassLedgeWater3BorderUpperLeft: 0,
  grassLedgeWater3BorderUpper: 0,
  grassLedgeWater3BorderUpperRight: 0,
  grassLedgeWater3BorderLeft: 0,
  grassLedgeWater3BorderRight: 0,
  grassLedgeWater3BorderLowerLeft: 0,
  grassLedgeWater3BorderLower: 0,
  grassLedgeWater3BorderLowerRight: 0,
  grassLedgeWater4BorderUpperLeft: 0,
  grassLedgeWater4BorderUpper: 0,
  grassLedgeWater4BorderUpperRight: 0,
  grassLedgeWater4BorderLeft: 0,
  grassLedgeWater4BorderRight: 0,
  grassLedgeWater4BorderLowerLeft: 0,
  grassLedgeWater4BorderLower: 0,
  grassLedgeWater4BorderLowerRight: 0,

  // Water animations with sand ledge border
  water1SandLedgeBorderUpperLeft: 0,
  water1SandLedgeBorderUpper: 0,
  water1SandLedgeBorderUpperRight: 0,
  water1SandLedgeBorderLeft: 0,
  water1SandLedgeBorderRight: 0,
  water1SandLedgeBorderLowerLeft: 0,
  water1SandLedgeBorderLower: 0,
  water1SandLedgeBorderLowerRight: 0,
  water2SandLedgeBorderUpperLeft: 0,
  water2SandLedgeBorderUpper: 0,
  water2SandLedgeBorderUpperRight: 0,
  water2SandLedgeBorderLeft: 0,
  water2SandLedgeBorderRight: 0,
  water2SandLedgeBorderLowerLeft: 0,
  water2SandLedgeBorderLower: 0,
  water2SandLedgeBorderLowerRight: 0,
  water3SandLedgeBorderUpperLeft: 0,
  water3SandLedgeBorderUpper: 0,
  water3SandLedgeBorderUpperRight: 0,
  water3SandLedgeBorderLeft: 0,
  water3SandLedgeBorderRight: 0,
  water3SandLedgeBorderLowerLeft: 0,
  water3SandLedgeBorderLower: 0,
  water3SandLedgeBorderLowerRight: 0,
  water4SandLedgeBorderUpperLeft: 0,
  water4SandLedgeBorderUpper: 0,
  water4SandLedgeBorderUpperRight: 0,
  water4SandLedgeBorderLeft: 0,
  water4SandLedgeBorderRight: 0,
  water4SandLedgeBorderLowerLeft: 0,
  water4SandLedgeBorderLower: 0,
  water4SandLedgeBorderLowerRight: 0,

  // Sand ledge with water animations border
  sandLedgeWater1BorderUpperLeft: 0,
  sandLedgeWater1BorderUpper: 0,
  sandLedgeWater1BorderUpperRight: 0,
  sandLedgeWater1BorderLeft: 0,
  sandLedgeWater1BorderRight: 0,
  sandLedgeWater1BorderLowerLeft: 0,
  sandLedgeWater1BorderLower: 0,
  sandLedgeWater1BorderLowerRight: 0,
  sandLedgeWater2BorderUpperLeft: 0,
  sandLedgeWater2BorderUpper: 0,
  sandLedgeWater2BorderUpperRight: 0,
  sandLedgeWater2BorderLeft: 0,
  sandLedgeWater2BorderRight: 0,
  sandLedgeWater2BorderLowerLeft: 0,
  sandLedgeWater2BorderLower: 0,
  sandLedgeWater2BorderLowerRight: 0,
  sandLedgeWater3BorderUpperLeft: 0,
  sandLedgeWater3BorderUpper: 0,
  sandLedgeWater3BorderUpperRight: 0,
  sandLedgeWater3BorderLeft: 0,
  sandLedgeWater3BorderRight: 0,
  sandLedgeWater3BorderLowerLeft: 0,
  sandLedgeWater3BorderLower: 0,
  sandLedgeWater3BorderLowerRight: 0,
  sandLedgeWater4BorderUpperLeft: 0,
  sandLedgeWater4BorderUpper: 0,
  sandLedgeWater4BorderUpperRight: 0,
  sandLedgeWater4BorderLeft: 0,
  sandLedgeWater4BorderRight: 0,
  sandLedgeWater4BorderLowerLeft: 0,
  sandLedgeWater4BorderLower: 0,
  sandLedgeWater4BorderLowerRight: 0,

  // Water animations with snow ledge border
  water1SnowLedgeBorderUpperLeft: 0,
  water1SnowLedgeBorderUpper: 0,
  water1SnowLedgeBorderUpperRight: 0,
  water1SnowLedgeBorderLeft: 0,
  water1SnowLedgeBorderRight: 0,
  water1SnowLedgeBorderLowerLeft: 0,
  water1SnowLedgeBorderLower: 0,
  water1SnowLedgeBorderLowerRight: 0,
  water2SnowLedgeBorderUpperLeft: 0,
  water2SnowLedgeBorderUpper: 0,
  water2SnowLedgeBorderUpperRight: 0,
  water2SnowLedgeBorderLeft: 0,
  water2SnowLedgeBorderRight: 0,
  water2SnowLedgeBorderLowerLeft: 0,
  water2SnowLedgeBorderLower: 0,
  water2SnowLedgeBorderLowerRight: 0,
  water3SnowLedgeBorderUpperLeft: 0,
  water3SnowLedgeBorderUpper: 0,
  water3SnowLedgeBorderUpperRight: 0,
  water3SnowLedgeBorderLeft: 0,
  water3SnowLedgeBorderRight: 0,
  water3SnowLedgeBorderLowerLeft: 0,
  water3SnowLedgeBorderLower: 0,
  water3SnowLedgeBorderLowerRight: 0,
  water4SnowLedgeBorderUpperLeft: 0,
  water4SnowLedgeBorderUpper: 0,
  water4SnowLedgeBorderUpperRight: 0,
  water4SnowLedgeBorderLeft: 0,
  water4SnowLedgeBorderRight: 0,
  water4SnowLedgeBorderLowerLeft: 0,
  water4SnowLedgeBorderLower: 0,
  water4SnowLedgeBorderLowerRight: 0,

  // Snow ledge with water animations border
  snowLedgeWater1BorderUpperLeft: 0,
  snowLedgeWater1BorderUpper: 0,
  snowLedgeWater1BorderUpperRight: 0,
  snowLedgeWater1BorderLeft: 0,
  snowLedgeWater1BorderRight: 0,
  snowLedgeWater1BorderLowerLeft: 0,
  snowLedgeWater1BorderLower: 0,
  snowLedgeWater1BorderLowerRight: 0,
  snowLedgeWater2BorderUpperLeft: 0,
  snowLedgeWater2BorderUpper: 0,
  snowLedgeWater2BorderUpperRight: 0,
  snowLedgeWater2BorderLeft: 0,
  snowLedgeWater2BorderRight: 0,
  snowLedgeWater2BorderLowerLeft: 0,
  snowLedgeWater2BorderLower: 0,
  snowLedgeWater2BorderLowerRight: 0,
  snowLedgeWater3BorderUpperLeft: 0,
  snowLedgeWater3BorderUpper: 0,
  snowLedgeWater3BorderUpperRight: 0,
  snowLedgeWater3BorderLeft: 0,
  snowLedgeWater3BorderRight: 0,
  snowLedgeWater3BorderLowerLeft: 0,
  snowLedgeWater3BorderLower: 0,
  snowLedgeWater3BorderLowerRight: 0,
  snowLedgeWater4BorderUpperLeft: 0,
  snowLedgeWater4BorderUpper: 0,
  snowLedgeWater4BorderUpperRight: 0,
  snowLedgeWater4BorderLeft: 0,
  snowLedgeWater4BorderRight: 0,
  snowLedgeWater4BorderLowerLeft: 0,
  snowLedgeWater4BorderLower: 0,
  snowLedgeWater4BorderLowerRight: 0,

  // Sand shore with water animations border
  sandShoreWater1BorderUpperLeft: 0,
  sandShoreWater1BorderUpper: 0,
  sandShoreWater1BorderUpperRight: 0,
  sandShoreWater1BorderLeft: 0,
  sandShoreWater1BorderRight: 0,
  sandShoreWater1BorderLowerLeft: 0,
  sandShoreWater1BorderLower: 0,
  sandShoreWater1BorderLowerRight: 0,
  sandShoreWater2BorderUpperLeft: 0,
  sandShoreWater2BorderUpper: 0,
  sandShoreWater2BorderUpperRight: 0,
  sandShoreWater2BorderLeft: 0,
  sandShoreWater2BorderRight: 0,
  sandShoreWater2BorderLowerLeft: 0,
  sandShoreWater2BorderLower: 0,
  sandShoreWater2BorderLowerRight: 0,
  sandShoreWater3BorderUpperLeft: 0,
  sandShoreWater3BorderUpper: 0,
  sandShoreWater3BorderUpperRight: 0,
  sandShoreWater3BorderLeft: 0,
  sandShoreWater3BorderRight: 0,
  sandShoreWater3BorderLowerLeft: 0,
  sandShoreWater3BorderLower: 0,
  sandShoreWater3BorderLowerRight: 0,
  sandShoreWater4BorderUpperLeft: 0,
  sandShoreWater4BorderUpper: 0,
  sandShoreWater4BorderUpperRight: 0,
  sandShoreWater4BorderLeft: 0,
  sandShoreWater4BorderRight: 0,
  sandShoreWater4BorderLowerLeft: 0,
  sandShoreWater4BorderLower: 0,
  sandShoreWater4BorderLowerRight: 0,

  // Water animations with sand shore border
  water1SandShoreBorderUpperLeft: 0,
  water1SandShoreBorderUpper: 0,
  water1SandShoreBorderUpperRight: 0,
  water1SandShoreBorderLeft: 0,
  water1SandShoreBorderRight: 0,
  water1SandShoreBorderLowerLeft: 0,
  water1SandShoreBorderLower: 0,
  water1SandShoreBorderLowerRight: 0,
  water2SandShoreBorderUpperLeft: 0,
  water2SandShoreBorderUpper: 0,
  water2SandShoreBorderUpperRight: 0,
  water2SandShoreBorderLeft: 0,
  water2SandShoreBorderRight: 0,
  water2SandShoreBorderLowerLeft: 0,
  water2SandShoreBorderLower: 0,
  water2SandShoreBorderLowerRight: 0,
  water3SandShoreBorderUpperLeft: 0,
  water3SandShoreBorderUpper: 0,
  water3SandShoreBorderUpperRight: 0,
  water3SandShoreBorderLeft: 0,
  water3SandShoreBorderRight: 0,
  water3SandShoreBorderLowerLeft: 0,
  water3SandShoreBorderLower: 0,
  water3SandShoreBorderLowerRight: 0,
  water4SandShoreBorderUpperLeft: 0,
  water4SandShoreBorderUpper: 0,
  water4SandShoreBorderUpperRight: 0,
  water4SandShoreBorderLeft: 0,
  water4SandShoreBorderRight: 0,
  water4SandShoreBorderLowerLeft: 0,
  water4SandShoreBorderLower: 0,
  water4SandShoreBorderLowerRight: 0,

  // Ice with snow ledge border
  iceSnowLedgeBorderUpperLeft: 0,
  iceSnowLedgeBorderUpper: 0,
  iceSnowLedgeBorderUpperRight: 0,
  iceSnowLedgeBorderLeft: 0,
  iceSnowLedgeBorderRight: 0,
  iceSnowLedgeBorderLowerLeft: 0,
  iceSnowLedgeBorderLower: 0,
  iceSnowLedgeBorderLowerRight: 0,

  // Snow ledge with ice border
  snowLedgeIceBorderUpperLeft: 0,
  snowLedgeIceBorderUpper: 0,
  snowLedgeIceBorderUpperRight: 0,
  snowLedgeIceBorderLeft: 0,
  snowLedgeIceBorderRight: 0,
  snowLedgeIceBorderLowerLeft: 0,
  snowLedgeIceBorderLower: 0,
  snowLedgeIceBorderLowerRight: 0,
} as const;
