import { RECEIVED_ITEM_FROM_B, TALKED_TO_A, TALKED_TO_B } from '../../../constants/storyFlags';
import type { LevelMap } from '../levelBuilder.types';

export const PURPLE_LEVEL: LevelMap = {
  id: 'purpleLevel',
  background: {
    resource: 'bgCave',
    frameSize: {
      x: 320,
      y: 180,
    },
  },
  heroDefaultPosition: {
    x: 0,
    y: 5,
  },
  exits: [
    {
      id: 'exitGrass1',
      newLevelId: 'grass1Level',
      x: 0,
      y: 4,
      heroNewPosition: {
        x: 6,
        y: 4,
      },
    },
  ],
  gameObjects: [
    {
      type: 'Chest',
      id: 'chest1',
      lootConfig: {
        item: 'rod2',
      },
      x: 0,
      y: 0,
    },
    {
      type: 'Chest',
      id: 'chest2',
      lootConfig: {
        item: 'hammer1',
      },
      interactionConfig: {
        content: [
          {
            string: ['You found an hammer'],
          },
        ],
      },
      x: 3,
      y: 0,
    },
    {
      type: 'Chest',
      id: 'chest3',
      lootConfig: {
        item: 'rod1',
      },
      interactionConfig: {
        content: [
          {
            string: ['You found a rod'],
          },
        ],
      },
      x: 4,
      y: 0,
    },
    {
      type: 'CollectibleItem',
      id: 'rod',
      item: 'rod2',
      x: 7,
      y: 5,
    },
    {
      type: 'CollectibleItem',
      id: 'heart',
      item: 'heart',
      x: 10,
      y: 3,
      shouldSkipPickupAnimation: true,
    },
    {
      type: 'Decoration',
      id: 'rock1-decoration',
      key: 'rock',
      x: 7,
      y: 0,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'rock2-decoration',
      key: 'rock',
      x: 10,
      y: 1,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'rock3-decoration',
      key: 'rock',
      x: 11,
      y: 1,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'rock4-decoration',
      key: 'rock',
      x: 11,
      y: 2,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'rock5-decoration',
      key: 'rock',
      x: 0,
      y: 3,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'stones1-decoration',
      key: 'stones',
      x: 1,
      y: 3,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'stones2-decoration',
      key: 'stones',
      x: 1,
      y: 4,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'rock6-decoration',
      key: 'rock',
      x: 0,
      y: 3,
      isSolid: true,
    },
    {
      type: 'Npc',
      id: 'npc1',
      x: 6,
      y: 3,
      npc: 'ow1',
      interactionConfig: {
        content: [
          {
            string: ["I just can't stand that guy."],
            requires: [TALKED_TO_B],
            bypass: [TALKED_TO_A],
            addsFlag: TALKED_TO_A,
          },
          {
            string: ['He is just the worst!'],
            requires: [TALKED_TO_A],
          },
          {
            string: ['Grumble grumble. Another day at work'],
          },
        ],
        portraitFrame: 1,
      },
    },
    {
      type: 'Npc',
      id: 'npc2',
      x: 9,
      y: 4,
      npc: 'ow2',
      interactionConfig: {
        content: [
          {
            string: ["Oh, here's your item"],
            requires: [TALKED_TO_B],
            bypass: [RECEIVED_ITEM_FROM_B],
            addsFlag: RECEIVED_ITEM_FROM_B,
            item: 'hammer1',
          },
          {
            string: ['Now you are more powerful!'],
            requires: [RECEIVED_ITEM_FROM_B],
          },
          {
            string: ['What a beautiful day to work in the cave!'],
            bypass: [TALKED_TO_B],
            addsFlag: TALKED_TO_B,
          },
        ],
        portraitFrame: 0,
      },
    },
    {
      type: 'Npc',
      id: 'npc3',
      x: 15,
      y: 6,
      npc: 'ow3',
      interactionConfig: {
        content: [
          {
            string: ['Go away!', "You're not welcomed here!"],
          },
        ],
        portraitFrame: 0,
      },
    },
  ],
  walls: [
    // Upper walls
    '0,-1',
    '1,-1',
    '2,-1',
    '3,-1',
    '4,-1',
    '5,-1',
    '6,-1',
    '7,-1',
    '8,-1',
    '9,-1',
    '10,-1',
    '11,-1',
    '12,-1',
    '13,-1',
    '14,-1',
    '15,-1',

    // Obstacle walls
    '1,0',
    '2,0',
    '3,2',
    '4,2',
    '6,2',
    '4,3',
    '5,3',
    '10,4',
    '11,4',
    '12,5',

    // Water walls
    '13,1',
    '14,1',
    '4,5',
    '5,5',
    '6,5',
    '9,5',
    '10,5',
    '11,5',

    // Left walls
    '-1,0',
    '-1,1',
    '-1,2',
    '-1,3',
    '-1,4',
    '-1,5',
    '-1,6',
    '-1,7',
    '-1,8',

    // Right walls
    '16,0',
    '16,1',
    '16,2',
    '16,3',
    '16,4',
    '16,5',
    '16,6',
    '16,7',
    '16,8',

    // Lower walls
    '0,7',
    '1,7',
    '2,7',
    '3,7',
    '4,7',
    '5,7',
    '6,7',
    '7,7',
    '8,7',
    '9,7',
    '10,7',
    '11,7',
    '12,7',
    '13,7',
    '14,7',
    '15,7',
  ],
  tiles: {
    // First row
    '0,0': 'purpleUpperLeft',
    '1,0': 'purpleObstacle',
    '2,0': 'purpleObstacle',
    '3,0': 'purpleUpper',
    '4,0': 'purpleUpper',
    '5,0': 'purpleUpper',
    '6,0': 'purpleUpper',
    '7,0': 'purpleUpper',
    '8,0': 'purpleUpper',
    '9,0': 'purpleUpper',
    '10,0': 'purpleUpper',
    '11,0': 'purpleUpper',
    '12,0': 'purpleUpper',
    '13,0': 'purpleUpper',
    '14,0': 'purpleUpper',
    '15,0': 'purpleUpperRight',
    // Second row
    '0,1': 'purpleLeft',
    '1,1': 'purple',
    '2,1': 'purple',
    '3,1': 'purple',
    '4,1': 'purple',
    '5,1': 'purple',
    '6,1': 'purple',
    '7,1': 'purple',
    '8,1': 'purple',
    '9,1': 'purple',
    '10,1': 'purple',
    '11,1': 'purple',
    '12,1': 'purple',
    '13,1': 'purpleWater',
    '14,1': 'purpleWater',
    '15,1': 'purpleRight',
    // Third row
    '0,2': 'purpleLeft',
    '1,2': 'purple',
    '2,2': 'purple',
    '3,2': 'purpleObstacle',
    '4,2': 'purpleObstacle',
    '5,2': 'purplePattern',
    '6,2': 'purpleObstacle',
    '7,2': 'purple',
    '8,2': 'purple',
    '9,2': 'purple',
    '10,2': 'purple',
    '11,2': 'purple',
    '12,2': 'purple',
    '13,2': 'purplePattern',
    '14,2': 'purple',
    '15,2': 'purpleRight',
    // Fourth row
    '0,3': 'purpleLeft',
    '1,3': 'purple',
    '2,3': 'purple',
    '3,3': 'purple',
    '4,3': 'purpleObstacle',
    '5,3': 'purpleObstacle',
    '6,3': 'purplePattern',
    '7,3': 'purple',
    '8,3': 'purple',
    '9,3': 'purple',
    '10,3': 'purple',
    '11,3': 'purple',
    '12,3': 'purple',
    '13,3': 'purple',
    '14,3': 'purple',
    '15,3': 'purpleRight',
    // Fifth row
    '0,4': 'purpleLeft',
    '1,4': 'purple',
    '2,4': 'purple',
    '3,4': 'purple',
    '4,4': 'purple',
    '5,4': 'purple',
    '6,4': 'purple',
    '7,4': 'purple',
    '8,4': 'purple',
    '9,4': 'purple',
    '10,4': 'purpleObstacle',
    '11,4': 'purpleObstacle',
    '12,4': 'purple',
    '13,4': 'purple',
    '14,4': 'purple',
    '15,4': 'purpleRight',
    // Sixth row
    '0,5': 'purpleLeft',
    '1,5': 'purple',
    '2,5': 'purplePattern',
    '3,5': 'purple',
    '4,5': 'purpleWater',
    '5,5': 'purpleWater',
    '6,5': 'purpleWater',
    '7,5': 'purple',
    '8,5': 'purple',
    '9,5': 'purpleWater',
    '10,5': 'purpleWater',
    '11,5': 'purpleWater',
    '12,5': 'purpleObstacle',
    '13,5': 'purplePattern',
    '14,5': 'purple',
    '15,5': 'purpleRight',
    // Seventh row
    '0,6': 'purpleLeft',
    '1,6': 'purple',
    '2,6': 'purple',
    '3,6': 'purple',
    '4,6': 'purple',
    '5,6': 'purple',
    '6,6': 'purple',
    '7,6': 'purple',
    '8,6': 'purple',
    '9,6': 'purple',
    '10,6': 'purple',
    '11,6': 'purple',
    '12,6': 'purple',
    '13,6': 'purple',
    '14,6': 'purple',
    '15,6': 'purpleRight',
    // Eighth row
    '0,7': 'purpleLowerLeft',
    '1,7': 'purpleLower',
    '2,7': 'purpleLower',
    '3,7': 'purpleLower',
    '4,7': 'purpleLower',
    '5,7': 'purpleLower',
    '6,7': 'purpleLower',
    '7,7': 'purpleLower',
    '8,7': 'purpleLower',
    '9,7': 'purpleLower',
    '10,7': 'purpleLower',
    '11,7': 'purpleLower',
    '12,7': 'purpleLower',
    '13,7': 'purpleLower',
    '14,7': 'purpleLower',
    '15,7': 'purpleLowerRight',
  },
};
