import type { LevelMap } from '../levelBuilder.types';

export const TEST_TILES_LEVEL: LevelMap = {
  id: 'testTilesMap',
  background: {
    resource: 'bgVolcano',
    frameSize: {
      x: 320,
      y: 180,
    },
  },
  heroDefaultPosition: {
    x: 0,
    y: 0,
  },
  exits: [],
  gameObjects: [
    {
      type: 'Decoration',
      id: 'tree1-upper-decoration',
      key: 'treeUpper',
      x: 0,
      y: -2,
      drawLayer: 'WORLD_TOP',
    },
    {
      type: 'Decoration',
      id: 'tree1-lower-decoration',
      key: 'treeLower',
      x: 0,
      y: -1,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'bush1-lower-decoration',
      key: 'bush1',
      x: 1,
      y: -1,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'stones-lower-decoration',
      key: 'stones',
      x: 2,
      y: -1,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'rock-lower-decoration',
      key: 'rock',
      x: 3,
      y: -1,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'house1-lower-decoration',
      key: 'house1',
      x: 4,
      y: -1,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'buildings-lower-decoration',
      key: 'buildings',
      x: 5,
      y: -1,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'house2-lower-decoration',
      key: 'house2',
      x: 6,
      y: -1,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'house3-lower-decoration',
      key: 'house3',
      x: 7,
      y: -1,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'house4-lower-decoration',
      key: 'house4',
      x: 8,
      y: -1,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'bush2-lower-decoration',
      key: 'bush2',
      x: 9,
      y: -1,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'tiles-lower-decoration',
      key: 'tiles',
      x: 10,
      y: -1,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'rocks-lower-decoration',
      key: 'rocks',
      x: 11,
      y: -1,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'house5-lower-decoration',
      key: 'house5',
      x: 12,
      y: -1,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'squareYellow-lower-decoration',
      key: 'squareYellow',
      x: 13,
      y: -1,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'squareCyan-lower-decoration',
      key: 'squareCyan',
      x: 14,
      y: -1,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'squareViolet-lower-decoration',
      key: 'squareViolet',
      x: 13,
      y: -2,
      isSolid: true,
    },
    {
      type: 'Decoration',
      id: 'squareOrange-lower-decoration',
      key: 'squareOrange',
      x: 14,
      y: -2,
      isSolid: true,
    },
  ],
  walls: [],
  tiles: {
    // First row
    '0,0': 'grass1UpperLeft',
    '1,0': 'grass1Upper',
    '2,0': 'grass1UpperRight',
    '3,0': 'grass1Pattern',
    '4,0': 'purpleUpperLeft',
    '5,0': 'purpleUpper',
    '6,0': 'purpleUpperRight',
    '7,0': 'purplePattern',
    '8,0': 'city1UpperLeft',
    '9,0': 'city1Upper',
    '10,0': 'city1UpperRight',
    '11,0': 'city1Pattern',
    '12,0': 'orangeUpperLeft',
    '13,0': 'orangeUpper',
    '14,0': 'orangeUpperRight',
    '15,0': 'orangePattern',
    // Second row
    '0,1': 'grass1Left',
    '1,1': 'grass1',
    '2,1': 'grass1Right',
    '3,1': 'grass1Water',
    '4,1': 'purpleLeft',
    '5,1': 'purple',
    '6,1': 'purpleRight',
    '7,1': 'purpleWater',
    '8,1': 'city1Left',
    '9,1': 'city1',
    '10,1': 'city1Right',
    '11,1': 'city1Water',
    '12,1': 'orangeLeft',
    '13,1': 'orange',
    '14,1': 'orangeRight',
    '15,1': 'orangeWater',
    // Third row
    '0,2': 'grass1LowerLeft',
    '1,2': 'grass1Lower',
    '2,2': 'grass1LowerRight',
    '3,2': 'grass1Obstacle',
    '4,2': 'purpleLowerLeft',
    '5,2': 'purpleLower',
    '6,2': 'purpleLowerRight',
    '7,2': 'purpleObstacle',
    '8,2': 'city1LowerLeft',
    '9,2': 'city1Lower',
    '10,2': 'city1LowerRight',
    '11,2': 'city1Obstacle',
    '12,2': 'orangeLowerLeft',
    '13,2': 'orangeLower',
    '14,2': 'orangeLowerRight',
    '15,2': 'orangeObstacle',
    // Fourth row
    '0,3': 'redUpperLeft',
    '1,3': 'redUpper',
    '2,3': 'redUpperRight',
    '3,3': 'redPattern',
    '4,3': 'blueUpperLeft',
    '5,3': 'blueUpper',
    '6,3': 'blueUpperRight',
    '7,3': 'bluePattern',
    '8,3': 'grass2UpperLeft',
    '9,3': 'grass2Upper',
    '10,3': 'grass2UpperRight',
    '11,3': 'grass2Pattern',
    '12,3': 'city2UpperLeft',
    '13,3': 'city2Upper',
    '14,3': 'city2UpperRight',
    '15,3': 'city2Pattern',
    // Fifth row
    '0,4': 'redLeft',
    '1,4': 'red',
    '2,4': 'redRight',
    '3,4': 'redWater',
    '4,4': 'blueLeft',
    '5,4': 'blue',
    '6,4': 'blueRight',
    '7,4': 'blueWater',
    '8,4': 'grass2Left',
    '9,4': 'grass2',
    '10,4': 'grass2Right',
    '11,4': 'grass2Water',
    '12,4': 'city2Left',
    '13,4': 'city2',
    '14,4': 'city2Right',
    '15,4': 'city2Water',
    // Sixth row
    '0,5': 'redLowerLeft',
    '1,5': 'redLower',
    '2,5': 'redLowerRight',
    '3,5': 'redObstacle',
    '4,5': 'blueLowerLeft',
    '5,5': 'blueLower',
    '6,5': 'blueLowerRight',
    '7,5': 'blueObstacle',
    '8,5': 'grass2LowerLeft',
    '9,5': 'grass2Lower',
    '10,5': 'grass2LowerRight',
    '11,5': 'grass2Obstacle',
    '12,5': 'city2LowerLeft',
    '13,5': 'city2Lower',
    '14,5': 'city2LowerRight',
    '15,5': 'city2Obstacle',
    // Seventh row
    '0,6': 'water',
    '1,6': 'lava',
  },
};
