// Hero events
export const HERO_POSITION = 'HERO_POSITION';
export const HERO_EXITS = 'HERO_EXITS';
export const HERO_REQUESTS_ACTION = 'HERO_REQUESTS_ACTION';
export const HERO_COLLECTS_ITEM = 'HERO_COLLECTS_ITEM';
export const HERO_OPENS_CHEST = 'HERO_OPENS_CHEST';
