import { z } from 'zod';
import type { ItemKey } from '../../objects/Item';
import type { Coords, Coords2D } from '../../types/coords';
import type { GameObjectDrawLayer } from '../GameObject';
import type {
  LevelCollectibleItem,
  LevelDecoration,
  LevelExit,
  LevelMap,
  LevelObjects,
  LevelsId,
} from '../LevelBuilder';
import type { LevelDecorationTileset, LevelTileName } from '../LevelBuilder/tileset.types';
import type { WorldBackground } from '../LevelBuilder/worldTiles.types';

export const LEVELS_IDS: LevelsId[] = ['tilesetLevel'] as const;
const GAME_OBJECT_DRAW_LAYERS: GameObjectDrawLayer[] = ['HUD', 'WORLD_TOP', 'FLOOR'] as const;
const WORLD_BACKGROUNDS: WorldBackground[] = ['bgCave', 'bgSky', 'bgVolcano'] as const;

const TILESET: LevelTileName[] = [
  'water',
  'grass',
  'sand',
  'snow',
  'bushBgGrass',
  'bushBgSand',
  'bushBgSnow',
  'ice',
  'sandGrassBorderUpperLeft',
  'sandGrassBorderUpperRight',
  'sandGrassBorderLowerLeft',
  'sandGrassBorderLowerRight',
  'sandGrassBorderUpper',
  'sandGrassBorderLower',
  'sandGrassBorderLeft',
  'sandGrassBorderRight',
  'grassSandBorderUpperLeft',
  'grassSandBorderUpperRight',
  'grassSandBorderLowerLeft',
  'grassSandBorderLowerRight',
  'grassSandBorderUpper',
  'grassSandBorderLower',
  'grassSandBorderLeft',
  'grassSandBorderRight',
  'grassCliffBorderUpperLeft',
  'grassCliffBorderUpperRight',
  'grassCliffBorderLowerLeft',
  'grassCliffBorderLowerRight',
  'grassCliffBorderUpper',
  'grassCliffBorderLower',
  'grassCliffBorderLeft',
  'grassCliffBorderRight',
  'cliffGrassBorderUpperLeft',
  'cliffGrassBorderUpperRight',
  'cliffGrassBorderLowerLeft',
  'cliffGrassBorderLowerRight',
  'cliffGrassBorderUpper',
  'cliffGrassBorderLower',
  'cliffGrassBorderLeft',
  'cliffGrassBorderRight',
  'sandCliffBorderUpperLeft',
  'sandCliffBorderUpperRight',
  'sandCliffBorderLowerLeft',
  'sandCliffBorderLowerRight',
  'sandCliffBorderUpper',
  'sandCliffBorderLower',
  'sandCliffBorderLeft',
  'sandCliffBorderRight',
  'cliffSandBorderUpperLeft',
  'cliffSandBorderUpperRight',
  'cliffSandBorderLowerLeft',
  'cliffSandBorderLowerRight',
  'cliffSandBorderUpper',
  'cliffSandBorderLower',
  'cliffSandBorderLeft',
  'cliffSandBorderRight',
  'snowCliffBorderUpperLeft',
  'snowCliffBorderUpperRight',
  'snowCliffBorderLowerLeft',
  'snowCliffBorderLowerRight',
  'snowCliffBorderUpper',
  'snowCliffBorderLower',
  'snowCliffBorderLeft',
  'snowCliffBorderRight',
  'cliffSnowBorderUpperLeft',
  'cliffSnowBorderUpperRight',
  'cliffSnowBorderLowerLeft',
  'cliffSnowBorderLowerRight',
  'cliffSnowBorderUpper',
  'cliffSnowBorderLower',
  'cliffSnowBorderLeft',
  'cliffSnowBorderRight',
  'snowGrassBorderUpperLeft',
  'snowGrassBorderUpperRight',
  'snowGrassBorderLowerLeft',
  'snowGrassBorderLowerRight',
  'snowGrassBorderUpper',
  'snowGrassBorderLower',
  'snowGrassBorderLeft',
  'snowGrassBorderRight',
  'grassSnowBorderUpperLeft',
  'grassSnowBorderUpperRight',
  'grassSnowBorderLowerLeft',
  'grassSnowBorderLowerRight',
  'grassSnowBorderUpper',
  'grassSnowBorderLower',
  'grassSnowBorderLeft',
  'grassSnowBorderRight',
  'grassLedgeBorderUpperLeft',
  'grassLedgeBorderUpperRight',
  'grassLedgeBorderLowerLeft',
  'grassLedgeBorderLowerRight',
  'grassLedgeBorderUpper',
  'grassLedgeBorderLower',
  'grassLedgeBorderLeft',
  'grassLedgeBorderRight',
  'ledgeGrassBorderUpperLeft',
  'ledgeGrassBorderUpperRight',
  'ledgeGrassBorderLowerLeft',
  'ledgeGrassBorderLowerRight',
  'ledgeGrassBorderUpper',
  'ledgeGrassBorderLower',
  'ledgeGrassBorderLeft',
  'ledgeGrassBorderRight',
  'ledgeGrassLower1',
  'ledgeGrassLower2',
  'ledgeGrassUpper1',
  'ledgeGrassUpper2',
  'ledgeGrassRight1',
  'ledgeGrassRight2',
  'ledgeGrassLeft1',
  'ledgeGrassLeft2',
  'grassStairs2stepsLower',
  'grassStairs3stepsLower',
  'grassStairs2stepsLeft',
  'grassStairs2stepsRight',
  'sandLedgeBorderUpperLeft',
  'sandLedgeBorderUpperRight',
  'sandLedgeBorderLowerLeft',
  'sandLedgeBorderLowerRight',
  'sandLedgeBorderUpper',
  'sandLedgeBorderLower',
  'sandLedgeBorderLeft',
  'sandLedgeBorderRight',
  'ledgeSandBorderUpperLeft',
  'ledgeSandBorderUpperRight',
  'ledgeSandBorderLowerLeft',
  'ledgeSandBorderLowerRight',
  'ledgeSandBorderUpper',
  'ledgeSandBorderLower',
  'ledgeSandBorderLeft',
  'ledgeSandBorderRight',
  'ledgeSandLower1',
  'ledgeSandLower2',
  'ledgeSandUpper1',
  'ledgeSandUpper2',
  'ledgeSandRight1',
  'ledgeSandRight2',
  'ledgeSandLeft1',
  'ledgeSandLeft2',
  'sandStairs2stepsLower',
  'sandStairs3stepsLower',
  'sandStairs2stepsLeft',
  'sandStairs2stepsRight',
  'snowLedgeBorderUpperLeft',
  'snowLedgeBorderUpperRight',
  'snowLedgeBorderLowerLeft',
  'snowLedgeBorderLowerRight',
  'snowLedgeBorderUpper',
  'snowLedgeBorderLower',
  'snowLedgeBorderLeft',
  'snowLedgeBorderRight',
  'ledgeSnowBorderUpperLeft',
  'ledgeSnowBorderUpperRight',
  'ledgeSnowBorderLowerLeft',
  'ledgeSnowBorderLowerRight',
  'ledgeSnowBorderUpper',
  'ledgeSnowBorderLower',
  'ledgeSnowBorderLeft',
  'ledgeSnowBorderRight',
  'ledgeSnowLower1',
  'ledgeSnowLower2',
  'ledgeSnowUpper1',
  'ledgeSnowUpper2',
  'ledgeSnowRight1',
  'ledgeSnowRight2',
  'ledgeSnowLeft1',
  'ledgeSnowLeft2',
  'snowStairs2stepsLower',
  'snowStairs3stepsLower',
  'snowStairs2stepsLeft',
  'snowStairs2stepsRight',
  'iceSnowLedgeBorderUpperLeft',
  'iceSnowLedgeBorderUpperRight',
  'iceSnowLedgeBorderLowerLeft',
  'iceSnowLedgeBorderLowerRight',
  'iceSnowLedgeBorderUpper',
  'iceSnowLedgeBorderLower',
  'iceSnowLedgeBorderLeft',
  'iceSnowLedgeBorderRight',
  'snowLedgeIceBorderUpperLeft',
  'snowLedgeIceBorderUpperRight',
  'snowLedgeIceBorderLowerLeft',
  'snowLedgeIceBorderLowerRight',
  'snowLedgeIceBorderUpper',
  'snowLedgeIceBorderLower',
  'snowLedgeIceBorderLeft',
  'snowLedgeIceBorderRight',
  'waterGrassLedgeBorderUpperLeft',
  'waterGrassLedgeBorderUpperRight',
  'waterGrassLedgeBorderLowerLeft',
  'waterGrassLedgeBorderLowerRight',
  'waterGrassLedgeBorderUpper',
  'waterGrassLedgeBorderLower',
  'waterGrassLedgeBorderLeft',
  'waterGrassLedgeBorderRight',
  'grassLedgeWaterBorderUpperLeft',
  'grassLedgeWaterBorderUpperRight',
  'grassLedgeWaterBorderLowerLeft',
  'grassLedgeWaterBorderLowerRight',
  'grassLedgeWaterBorderUpper',
  'grassLedgeWaterBorderLower',
  'grassLedgeWaterBorderLeft',
  'grassLedgeWaterBorderRight',
  'waterSandLedgeBorderUpperLeft',
  'waterSandLedgeBorderUpperRight',
  'waterSandLedgeBorderLowerLeft',
  'waterSandLedgeBorderLowerRight',
  'waterSandLedgeBorderUpper',
  'waterSandLedgeBorderLower',
  'waterSandLedgeBorderLeft',
  'waterSandLedgeBorderRight',
  'sandLedgeWaterBorderUpperLeft',
  'sandLedgeWaterBorderUpperRight',
  'sandLedgeWaterBorderLowerLeft',
  'sandLedgeWaterBorderLowerRight',
  'sandLedgeWaterBorderUpper',
  'sandLedgeWaterBorderLower',
  'sandLedgeWaterBorderLeft',
  'sandLedgeWaterBorderRight',
  'waterSnowLedgeBorderUpperLeft',
  'waterSnowLedgeBorderUpperRight',
  'waterSnowLedgeBorderLowerLeft',
  'waterSnowLedgeBorderLowerRight',
  'waterSnowLedgeBorderUpper',
  'waterSnowLedgeBorderLower',
  'waterSnowLedgeBorderLeft',
  'waterSnowLedgeBorderRight',
  'snowLedgeWaterBorderUpperLeft',
  'snowLedgeWaterBorderUpperRight',
  'snowLedgeWaterBorderLowerLeft',
  'snowLedgeWaterBorderLowerRight',
  'snowLedgeWaterBorderUpper',
  'snowLedgeWaterBorderLower',
  'snowLedgeWaterBorderLeft',
  'snowLedgeWaterBorderRight',
  'sandShoreWaterBorderUpperLeft',
  'sandShoreWaterBorderUpperRight',
  'sandShoreWaterBorderLowerLeft',
  'sandShoreWaterBorderLowerRight',
  'sandShoreWaterBorderUpper',
  'sandShoreWaterBorderLower',
  'sandShoreWaterBorderLeft',
  'sandShoreWaterBorderRight',
  'waterSandShoreBorderUpperLeft',
  'waterSandShoreBorderUpperRight',
  'waterSandShoreBorderLowerLeft',
  'waterSandShoreBorderLowerRight',
  'waterSandShoreBorderUpper',
  'waterSandShoreBorderLower',
  'waterSandShoreBorderLeft',
  'waterSandShoreBorderRight',
] as const;

const TILESET_DECORATIONS: LevelDecorationTileset[] = [
  'bushBgTransparent',
  'rock1BaseGrass',
  'rock1BaseSand',
  'rock1BaseSnow',
  'rock2BaseGrass',
  'rock2BaseSand',
  'rock2BaseSnow',
] as const;

const ITEM_KEYS: ItemKey[] = [
  'hammer1',
  'hammer2',
  'slingshot1',
  'slingshot2',
  'rod1',
  'rod2',
  'potion1',
  'potion2',
  'heart',
  'sword',
] as const;

/**
 * Zod schema for validating LevelMap JSON data
 * Inferred from the LevelMap TypeScript interface to ensure consistency
 */

const LevelIdSchema = z.enum(LEVELS_IDS) satisfies z.ZodType<LevelsId>;

const Coords2DSchema = z.object({
  x: z.number().int(),
  y: z.number().int(),
}) satisfies z.ZodType<Coords2D>;

const LevelBackgroundSchema = z.object({
  resource: z.enum(WORLD_BACKGROUNDS),
  frameSize: Coords2DSchema,
}) satisfies z.ZodType<LevelMap['background']>;

const LevelExitSchema = z.object({
  type: z.literal('Exit'),
  id: z.string(),
  newLevelId: LevelIdSchema,
  x: z.number().int(),
  y: z.number().int(),
  heroNewPosition: Coords2DSchema,
}) satisfies z.ZodType<LevelExit>;

const LevelCollectibleItemSchema = z.object({
  type: z.literal('CollectibleItem'),
  id: z.string(),
  item: z.enum(ITEM_KEYS),
  x: z.number().int(),
  y: z.number().int(),
}) satisfies z.ZodType<LevelCollectibleItem>;

const LevelDecorationSchema = z.object({
  type: z.literal('Decoration'),
  id: z.string(),
  key: z.enum(TILESET_DECORATIONS),
  x: z.number().int(),
  y: z.number().int(),
  isSolid: z.boolean().optional(),
  drawLayer: z.enum(GAME_OBJECT_DRAW_LAYERS).optional(),
}) satisfies z.ZodType<LevelDecoration>;

const LevelObjectsSchema = z.union([
  LevelCollectibleItemSchema,
  LevelDecorationSchema,
  LevelExitSchema,
]) satisfies z.ZodType<LevelObjects>;

const WallCoordSchema = z.templateLiteral([
  z.number().int(),
  z.literal(','),
  z.number().int(),
]) satisfies z.ZodType<Coords>;

/**
 * Main LevelMap schema for JSON validation
 * Each level has its own JSON file that must conform to this schema
 * Inferred from the LevelMap TypeScript interface
 */
export const LevelMapJsonSchema = z.object({
  id: LevelIdSchema,
  background: LevelBackgroundSchema,
  heroDefaultPosition: Coords2DSchema,
  gameObjects: z.array(LevelObjectsSchema),
  walls: z.array(WallCoordSchema),
  tiles: z.record(WallCoordSchema, z.enum(TILESET).nullable()),
}) satisfies z.ZodType<LevelMap>;

export type LevelMapJsonType = z.infer<typeof LevelMapJsonSchema>;
