import { z } from 'zod';
import type { ChestStatus } from '../../objects/Chest';
import type { ItemKey } from '../../objects/Item';
import type { NpcBehavior } from '../../objects/Npc';
import type { Coords, Coords2D } from '../../types/coords';
import type { Directions } from '../../types/directions';
import type { GameObjectBehavior, GameObjectDrawLayer } from '../GameObject';
import type {
  LevelChestItem,
  LevelCollectibleItem,
  LevelDecoration,
  LevelExit,
  LevelMap,
  LevelNpc,
  LevelObjects,
  LevelsId,
} from '../LevelBuilder';
import type { LevelDecorationTileset, LevelTileName } from '../LevelBuilder/tileset.types';
import type { BgKey, NpcKey } from '../Resources';

export const LEVELS_IDS: readonly LevelsId[] = ['tilesetLevel', 'tilesetLevel2'];
const GAME_OBJECT_DRAW_LAYERS: readonly GameObjectDrawLayer[] = ['HUD', 'WORLD_TOP', 'FLOOR'];
const WORLD_BACKGROUNDS: readonly BgKey[] = ['bgCave', 'bgSky', 'bgVolcano'];
const NPC_KEYS: readonly NpcKey[] = ['ow1', 'ow2', 'ow3', 'ow4', 'ow5', 'ow6', 'ow7', 'ow8', 'ow9', 'ow10'];
const CHEST_STATUSES: readonly ChestStatus[] = ['OPEN', 'CLOSED'];
const DIRECTIONS: readonly Directions[] = ['LEFT', 'RIGHT', 'UP', 'DOWN'];

const TILESET: readonly LevelTileName[] = [
  'grass',
  'sand',
  'snow',
  'tallGrassBgGrass',
  'tallGrassBgSand',
  'tallGrassBgSnow',
  'ice',
  'sandGrassBorder',
  'sandGrassBorderUpper',
  'sandGrassBorderLower',
  'sandGrassBorderLeft',
  'sandGrassBorderRight',
  'sandGrassBorderUpperLeft',
  'sandGrassBorderUpperRight',
  'sandGrassBorderLowerLeft',
  'sandGrassBorderLowerRight',
  'grassSandBorder',
  'grassSandBorderUpper',
  'grassSandBorderLower',
  'grassSandBorderLeft',
  'grassSandBorderRight',
  'grassSandBorderUpperLeft',
  'grassSandBorderUpperRight',
  'grassSandBorderLowerLeft',
  'grassSandBorderLowerRight',
  'grassCliffBorder',
  'grassCliffBorderUpper',
  'grassCliffBorderLower',
  'grassCliffBorderLeft',
  'grassCliffBorderRight',
  'grassCliffBorderUpperLeft',
  'grassCliffBorderUpperRight',
  'grassCliffBorderLowerLeft',
  'grassCliffBorderLowerRight',
  'cliffGrassBorder',
  'cliffGrassBorderUpper',
  'cliffGrassBorderLower',
  'cliffGrassBorderLeft',
  'cliffGrassBorderRight',
  'cliffGrassBorderUpperLeft',
  'cliffGrassBorderUpperRight',
  'cliffGrassBorderLowerLeft',
  'cliffGrassBorderLowerRight',
  'sandCliffBorder',
  'sandCliffBorderUpper',
  'sandCliffBorderLower',
  'sandCliffBorderLeft',
  'sandCliffBorderRight',
  'sandCliffBorderUpperLeft',
  'sandCliffBorderUpperRight',
  'sandCliffBorderLowerLeft',
  'sandCliffBorderLowerRight',
  'cliffSandBorder',
  'cliffSandBorderUpper',
  'cliffSandBorderLower',
  'cliffSandBorderLeft',
  'cliffSandBorderRight',
  'cliffSandBorderUpperLeft',
  'cliffSandBorderUpperRight',
  'cliffSandBorderLowerLeft',
  'cliffSandBorderLowerRight',
  'snowCliffBorder',
  'snowCliffBorderUpper',
  'snowCliffBorderLower',
  'snowCliffBorderLeft',
  'snowCliffBorderRight',
  'snowCliffBorderUpperLeft',
  'snowCliffBorderUpperRight',
  'snowCliffBorderLowerLeft',
  'snowCliffBorderLowerRight',
  'cliffSnowBorder',
  'cliffSnowBorderUpper',
  'cliffSnowBorderLower',
  'cliffSnowBorderLeft',
  'cliffSnowBorderRight',
  'cliffSnowBorderUpperLeft',
  'cliffSnowBorderUpperRight',
  'cliffSnowBorderLowerLeft',
  'cliffSnowBorderLowerRight',
  'snowGrassBorder',
  'snowGrassBorderUpper',
  'snowGrassBorderLower',
  'snowGrassBorderLeft',
  'snowGrassBorderRight',
  'snowGrassBorderUpperLeft',
  'snowGrassBorderUpperRight',
  'snowGrassBorderLowerLeft',
  'snowGrassBorderLowerRight',
  'grassSnowBorder',
  'grassSnowBorderUpper',
  'grassSnowBorderLower',
  'grassSnowBorderLeft',
  'grassSnowBorderRight',
  'grassSnowBorderUpperLeft',
  'grassSnowBorderUpperRight',
  'grassSnowBorderLowerLeft',
  'grassSnowBorderLowerRight',
  'grassLedgeBorder',
  'grassLedgeBorderUpper',
  'grassLedgeBorderLower',
  'grassLedgeBorderLeft',
  'grassLedgeBorderRight',
  'grassLedgeBorderUpperLeft',
  'grassLedgeBorderUpperRight',
  'grassLedgeBorderLowerLeft',
  'grassLedgeBorderLowerRight',
  'ledgeGrassBorder',
  'ledgeGrassBorderUpper',
  'ledgeGrassBorderLower',
  'ledgeGrassBorderLeft',
  'ledgeGrassBorderRight',
  'ledgeGrassBorderUpperLeft',
  'ledgeGrassBorderUpperRight',
  'ledgeGrassBorderLowerLeft',
  'ledgeGrassBorderLowerRight',
  'ledgeGrassLower1',
  'ledgeGrassLower2',
  'ledgeGrassUpper1',
  'ledgeGrassUpper2',
  'ledgeGrassRight1',
  'ledgeGrassRight2',
  'ledgeGrassLeft1',
  'ledgeGrassLeft2',
  'grassStairs2stepsLower',
  'grassStairs3stepsLower',
  'grassStairs2stepsLeft',
  'grassStairs2stepsRight',
  'sandLedgeBorder',
  'sandLedgeBorderUpper',
  'sandLedgeBorderLower',
  'sandLedgeBorderLeft',
  'sandLedgeBorderRight',
  'sandLedgeBorderUpperLeft',
  'sandLedgeBorderUpperRight',
  'sandLedgeBorderLowerLeft',
  'sandLedgeBorderLowerRight',
  'ledgeSandBorder',
  'ledgeSandBorderUpper',
  'ledgeSandBorderLower',
  'ledgeSandBorderLeft',
  'ledgeSandBorderRight',
  'ledgeSandBorderUpperLeft',
  'ledgeSandBorderUpperRight',
  'ledgeSandBorderLowerLeft',
  'ledgeSandBorderLowerRight',
  'ledgeSandLower1',
  'ledgeSandLower2',
  'ledgeSandUpper1',
  'ledgeSandUpper2',
  'ledgeSandRight1',
  'ledgeSandRight2',
  'ledgeSandLeft1',
  'ledgeSandLeft2',
  'sandStairs2stepsLower',
  'sandStairs3stepsLower',
  'sandStairs2stepsLeft',
  'sandStairs2stepsRight',
  'snowLedgeBorder',
  'snowLedgeBorderUpper',
  'snowLedgeBorderLower',
  'snowLedgeBorderLeft',
  'snowLedgeBorderRight',
  'snowLedgeBorderUpperLeft',
  'snowLedgeBorderUpperRight',
  'snowLedgeBorderLowerLeft',
  'snowLedgeBorderLowerRight',
  'ledgeSnowBorder',
  'ledgeSnowBorderUpper',
  'ledgeSnowBorderLower',
  'ledgeSnowBorderLeft',
  'ledgeSnowBorderRight',
  'ledgeSnowBorderUpperLeft',
  'ledgeSnowBorderUpperRight',
  'ledgeSnowBorderLowerLeft',
  'ledgeSnowBorderLowerRight',
  'ledgeSnowLower1',
  'ledgeSnowLower2',
  'ledgeSnowUpper1',
  'ledgeSnowUpper2',
  'ledgeSnowRight1',
  'ledgeSnowRight2',
  'ledgeSnowLeft1',
  'ledgeSnowLeft2',
  'snowStairs2stepsLower',
  'snowStairs3stepsLower',
  'snowStairs2stepsLeft',
  'snowStairs2stepsRight',
  'iceSnowLedgeBorder',
  'iceSnowLedgeBorderUpper',
  'iceSnowLedgeBorderLower',
  'iceSnowLedgeBorderLeft',
  'iceSnowLedgeBorderRight',
  'iceSnowLedgeBorderUpperLeft',
  'iceSnowLedgeBorderUpperRight',
  'iceSnowLedgeBorderLowerLeft',
  'iceSnowLedgeBorderLowerRight',
  'snowLedgeIceBorder',
  'snowLedgeIceBorderUpper',
  'snowLedgeIceBorderLower',
  'snowLedgeIceBorderLeft',
  'snowLedgeIceBorderRight',
  'snowLedgeIceBorderUpperLeft',
  'snowLedgeIceBorderUpperRight',
  'snowLedgeIceBorderLowerLeft',
  'snowLedgeIceBorderLowerRight',
  'flowerSmRedBgGrass',
  'flowerSmRedBgSand',
  'flowerSmRedBgSnow',
  'flowerSmBlueBgGrass',
  'flowerSmBlueBgSand',
  'flowerSmBlueBgSnow',
  'flowerSmYellowBgGrass',
  'flowerSmYellowBgSand',
  'flowerSmYellowBgSnow',
  'flowerMdRedBgGrass',
  'flowerMdRedBgSand',
  'flowerMdRedBgSnow',
  'flowerMdBlueBgGrass',
  'flowerMdBlueBgSand',
  'flowerMdBlueBgSnow',
  'flowerMdYellowBgGrass',
  'flowerMdYellowBgSand',
  'flowerMdYellowBgSnow',
  'flowerLgRedBgGrass',
  'flowerLgRedBgSand',
  'flowerLgRedBgSnow',
  'flowerLgBlueBgGrass',
  'flowerLgBlueBgSand',
  'flowerLgBlueBgSnow',
  'flowerLgYellowBgGrass',
  'flowerLgYellowBgSand',
  'flowerLgYellowBgSnow',
  'waterAnimated',
  'waterAnimatedGrassLedgeBorder',
  'waterAnimatedGrassLedgeBorderUpper',
  'waterAnimatedGrassLedgeBorderLower',
  'waterAnimatedGrassLedgeBorderLeft',
  'waterAnimatedGrassLedgeBorderRight',
  'waterAnimatedGrassLedgeBorderUpperLeft',
  'waterAnimatedGrassLedgeBorderUpperRight',
  'waterAnimatedGrassLedgeBorderLowerLeft',
  'waterAnimatedGrassLedgeBorderLowerRight',
  'grassLedgeWaterAnimatedBorder',
  'grassLedgeWaterAnimatedBorderUpper',
  'grassLedgeWaterAnimatedBorderLower',
  'grassLedgeWaterAnimatedBorderLeft',
  'grassLedgeWaterAnimatedBorderRight',
  'grassLedgeWaterAnimatedBorderUpperLeft',
  'grassLedgeWaterAnimatedBorderUpperRight',
  'grassLedgeWaterAnimatedBorderLowerLeft',
  'grassLedgeWaterAnimatedBorderLowerRight',
  'waterAnimatedSandLedgeBorder',
  'waterAnimatedSandLedgeBorderUpper',
  'waterAnimatedSandLedgeBorderLower',
  'waterAnimatedSandLedgeBorderLeft',
  'waterAnimatedSandLedgeBorderRight',
  'waterAnimatedSandLedgeBorderUpperLeft',
  'waterAnimatedSandLedgeBorderUpperRight',
  'waterAnimatedSandLedgeBorderLowerLeft',
  'waterAnimatedSandLedgeBorderLowerRight',
  'sandLedgeWaterAnimatedBorder',
  'sandLedgeWaterAnimatedBorderUpper',
  'sandLedgeWaterAnimatedBorderLower',
  'sandLedgeWaterAnimatedBorderLeft',
  'sandLedgeWaterAnimatedBorderRight',
  'sandLedgeWaterAnimatedBorderUpperLeft',
  'sandLedgeWaterAnimatedBorderUpperRight',
  'sandLedgeWaterAnimatedBorderLowerLeft',
  'sandLedgeWaterAnimatedBorderLowerRight',
  'waterAnimatedSnowLedgeBorder',
  'waterAnimatedSnowLedgeBorderUpper',
  'waterAnimatedSnowLedgeBorderLower',
  'waterAnimatedSnowLedgeBorderLeft',
  'waterAnimatedSnowLedgeBorderRight',
  'waterAnimatedSnowLedgeBorderUpperLeft',
  'waterAnimatedSnowLedgeBorderUpperRight',
  'waterAnimatedSnowLedgeBorderLowerLeft',
  'waterAnimatedSnowLedgeBorderLowerRight',
  'snowLedgeWaterAnimatedBorder',
  'snowLedgeWaterAnimatedBorderUpper',
  'snowLedgeWaterAnimatedBorderLower',
  'snowLedgeWaterAnimatedBorderLeft',
  'snowLedgeWaterAnimatedBorderRight',
  'snowLedgeWaterAnimatedBorderUpperLeft',
  'snowLedgeWaterAnimatedBorderUpperRight',
  'snowLedgeWaterAnimatedBorderLowerLeft',
  'snowLedgeWaterAnimatedBorderLowerRight',
  'sandShoreWaterAnimatedBorder',
  'sandShoreWaterAnimatedBorderUpper',
  'sandShoreWaterAnimatedBorderLower',
  'sandShoreWaterAnimatedBorderLeft',
  'sandShoreWaterAnimatedBorderRight',
  'sandShoreWaterAnimatedBorderUpperLeft',
  'sandShoreWaterAnimatedBorderUpperRight',
  'sandShoreWaterAnimatedBorderLowerLeft',
  'sandShoreWaterAnimatedBorderLowerRight',
  'waterAnimatedSandShoreBorder',
  'waterAnimatedSandShoreBorderUpper',
  'waterAnimatedSandShoreBorderLower',
  'waterAnimatedSandShoreBorderLeft',
  'waterAnimatedSandShoreBorderRight',
  'waterAnimatedSandShoreBorderUpperLeft',
  'waterAnimatedSandShoreBorderUpperRight',
  'waterAnimatedSandShoreBorderLowerLeft',
  'waterAnimatedSandShoreBorderLowerRight',
  'water',
  'waterGrassLedgeBorder',
  'waterGrassLedgeBorderUpper',
  'waterGrassLedgeBorderLower',
  'waterGrassLedgeBorderLeft',
  'waterGrassLedgeBorderRight',
  'waterGrassLedgeBorderUpperLeft',
  'waterGrassLedgeBorderUpperRight',
  'waterGrassLedgeBorderLowerLeft',
  'waterGrassLedgeBorderLowerRight',
  'grassLedgeWaterBorder',
  'grassLedgeWaterBorderUpper',
  'grassLedgeWaterBorderLower',
  'grassLedgeWaterBorderLeft',
  'grassLedgeWaterBorderRight',
  'grassLedgeWaterBorderUpperLeft',
  'grassLedgeWaterBorderUpperRight',
  'grassLedgeWaterBorderLowerLeft',
  'grassLedgeWaterBorderLowerRight',
  'waterSandLedgeBorder',
  'waterSandLedgeBorderUpper',
  'waterSandLedgeBorderLower',
  'waterSandLedgeBorderLeft',
  'waterSandLedgeBorderRight',
  'waterSandLedgeBorderUpperLeft',
  'waterSandLedgeBorderUpperRight',
  'waterSandLedgeBorderLowerLeft',
  'waterSandLedgeBorderLowerRight',
  'sandLedgeWaterBorder',
  'sandLedgeWaterBorderUpper',
  'sandLedgeWaterBorderLower',
  'sandLedgeWaterBorderLeft',
  'sandLedgeWaterBorderRight',
  'sandLedgeWaterBorderUpperLeft',
  'sandLedgeWaterBorderUpperRight',
  'sandLedgeWaterBorderLowerLeft',
  'sandLedgeWaterBorderLowerRight',
  'waterSnowLedgeBorder',
  'waterSnowLedgeBorderUpper',
  'waterSnowLedgeBorderLower',
  'waterSnowLedgeBorderLeft',
  'waterSnowLedgeBorderRight',
  'waterSnowLedgeBorderUpperLeft',
  'waterSnowLedgeBorderUpperRight',
  'waterSnowLedgeBorderLowerLeft',
  'waterSnowLedgeBorderLowerRight',
  'snowLedgeWaterBorder',
  'snowLedgeWaterBorderUpper',
  'snowLedgeWaterBorderLower',
  'snowLedgeWaterBorderLeft',
  'snowLedgeWaterBorderRight',
  'snowLedgeWaterBorderUpperLeft',
  'snowLedgeWaterBorderUpperRight',
  'snowLedgeWaterBorderLowerLeft',
  'snowLedgeWaterBorderLowerRight',
  'sandShoreWaterBorder',
  'sandShoreWaterBorderUpper',
  'sandShoreWaterBorderLower',
  'sandShoreWaterBorderLeft',
  'sandShoreWaterBorderRight',
  'sandShoreWaterBorderUpperLeft',
  'sandShoreWaterBorderUpperRight',
  'sandShoreWaterBorderLowerLeft',
  'sandShoreWaterBorderLowerRight',
  'waterSandShoreBorder',
  'waterSandShoreBorderUpper',
  'waterSandShoreBorderLower',
  'waterSandShoreBorderLeft',
  'waterSandShoreBorderRight',
  'waterSandShoreBorderUpperLeft',
  'waterSandShoreBorderUpperRight',
  'waterSandShoreBorderLowerLeft',
  'waterSandShoreBorderLowerRight',
];

const TILESET_DECORATIONS: LevelDecorationTileset[] = [
  'tallGrass',
  'rock1BaseGrass',
  'rock1BaseSand',
  'rock1BaseSnow',
  'rock2BaseGrass',
  'rock2BaseSand',
  'rock2BaseSnow',
  'spruceSnow1UpperLeft',
  'spruceSnow1UpperRight',
  'spruceSnow1LowerLeft',
  'spruceSnow1LowerRight',
  'spruceSnow1MiddleLeft',
  'spruceSnow1MiddleRight',
  'spruceSnow2UpperLeft',
  'spruceSnow2UpperRight',
  'spruceSnow2LowerLeft',
  'spruceSnow2LowerRight',
  'spruceSnow2MiddleLeft',
  'spruceSnow2MiddleRight',
  'spruceGreenUpperLeft',
  'spruceGreenUpperRight',
  'spruceGreenLowerLeft',
  'spruceGreenLowerRight',
  'spruceGreenMiddleLeft',
  'spruceGreenMiddleRight',
  'palmLg1UpperLeft',
  'palmLg1UpperRight',
  'palmLg1LowerLeft',
  'palmLg1LowerRight',
  'palmLg1MiddleLeft',
  'palmLg1MiddleRight',
  'palmLg2UpperLeft',
  'palmLg2UpperRight',
  'palmLg2LowerLeft',
  'palmLg2LowerRight',
  'palmLg2MiddleLeft',
  'palmLg2MiddleRight',
  'palmSmUpper',
  'palmSmLower',
  'treeLgSnowUpperLeft',
  'treeLgSnowUpperRight',
  'treeLgSnowLowerLeft',
  'treeLgSnowLowerRight',
  'treeLgSnowMiddleLeft',
  'treeLgSnowMiddleRight',
  'treeLgGreenUpperLeft',
  'treeLgGreenUpperRight',
  'treeLgGreenLowerLeft',
  'treeLgGreenLowerRight',
  'treeLgGreenMiddleLeft',
  'treeLgGreenMiddleRight',
  'treeSmSnowUpper',
  'treeSmSnowLower',
  'treeSmGreenUpper',
  'treeSmGreenLower',
  'flowerSmRedBaseGrass',
  'flowerSmRedBaseSand',
  'flowerSmRedBaseSnow',
  'flowerSmBlueBaseGrass',
  'flowerSmBlueBaseSand',
  'flowerSmBlueBaseSnow',
  'flowerSmYellowBaseGrass',
  'flowerSmYellowBaseSand',
  'flowerSmYellowBaseSnow',
  'flowerMdRedBaseGrass',
  'flowerMdRedBaseSand',
  'flowerMdRedBaseSnow',
  'flowerMdBlueBaseGrass',
  'flowerMdBlueBaseSand',
  'flowerMdBlueBaseSnow',
  'flowerMdYellowBaseGrass',
  'flowerMdYellowBaseSand',
  'flowerMdYellowBaseSnow',
  'flowerLgRedBaseGrass',
  'flowerLgRedBaseSand',
  'flowerLgRedBaseSnow',
  'flowerLgBlueBaseGrass',
  'flowerLgBlueBaseSand',
  'flowerLgBlueBaseSnow',
  'flowerLgYellowBaseGrass',
  'flowerLgYellowBaseSand',
  'flowerLgYellowBaseSnow',
];

const ITEM_KEYS: readonly ItemKey[] = [
  'hammer1',
  'hammer2',
  'slingshot1',
  'slingshot2',
  'rod1',
  'rod2',
  'potion1',
  'potion2',
  'heart',
  'sword',
];

/**
 * Zod schema for validating LevelMap JSON data
 * Inferred from the LevelMap TypeScript interface to ensure consistency
 */

const LevelIdSchema = z.enum(LEVELS_IDS) satisfies z.ZodType<LevelsId>;

const Coords2DSchema = z.object({
  x: z.number().int(),
  y: z.number().int(),
}) satisfies z.ZodType<Coords2D>;

const LevelBackgroundSchema = z.object({
  resource: z.enum(WORLD_BACKGROUNDS),
  frameSize: Coords2DSchema,
}) satisfies z.ZodType<LevelMap['background']>;

const InteractionContentConfigSchema = z.object({
  text: z.array(z.string()),
  requires: z.array(z.string()).optional(),
  bypass: z.array(z.string()).optional(),
  addsFlag: z.string().optional(),
  item: z.enum(ITEM_KEYS).optional(),
});

const InteractionConfigSchema = z.object({
  portraitFrame: z.number().int().nullable().optional(),
  content: z.array(InteractionContentConfigSchema),
});

const GameObjectBehaviorSchema = z.object({
  type: z.unknown(),
  direction: z.enum(DIRECTIONS),
}) satisfies z.ZodType<GameObjectBehavior>;

const LevelExitSchema = z.object({
  type: z.literal('Exit'),
  id: z.string(),
  newLevelId: LevelIdSchema,
  x: z.number().int(),
  y: z.number().int(),
  behaviorConfig: z.array(GameObjectBehaviorSchema).optional(),
  newHeroPosition: Coords2DSchema,
}) satisfies z.ZodType<LevelExit>;

const LevelCollectibleItemSchema = z.object({
  type: z.literal('CollectibleItem'),
  id: z.string(),
  itemKey: z.enum(ITEM_KEYS),
  x: z.number().int(),
  y: z.number().int(),
  behaviorConfig: z.array(GameObjectBehaviorSchema).optional(),
  skipCollectAnimation: z.boolean().optional(),
}) satisfies z.ZodType<LevelCollectibleItem>;

const LevelDecorationSchema = z.object({
  type: z.literal('Decoration'),
  id: z.string(),
  key: z.enum(TILESET_DECORATIONS),
  x: z.number().int(),
  y: z.number().int(),
  isSolid: z.boolean().optional(),
  drawLayer: z.enum(GAME_OBJECT_DRAW_LAYERS).optional(),
  behaviorConfig: z.array(GameObjectBehaviorSchema).optional(),
}) satisfies z.ZodType<LevelDecoration>;

const LevelChestSchema = z.object({
  type: z.literal('Chest'),
  id: z.string(),
  x: z.number().int(),
  y: z.number().int(),
  behaviorConfig: z.array(GameObjectBehaviorSchema).optional(),
  status: z.enum(CHEST_STATUSES).optional(),
  removeAfterLoot: z.boolean().optional(),
  interactionConfig: InteractionConfigSchema,
}) satisfies z.ZodType<LevelChestItem>;

const NpcBehaviorSchema = z.discriminatedUnion('type', [
  z.object({
    type: z.literal('walk'),
    direction: z.enum(DIRECTIONS),
    speed: z.number().optional(),
  }),
  z.object({
    type: z.literal('stand'),
    direction: z.enum(DIRECTIONS),
    duration: z.number().optional(),
  }),
]) satisfies z.ZodType<NpcBehavior>;

const LevelNpcSchema = z.object({
  type: z.literal('Npc'),
  id: z.string(),
  x: z.number().int(),
  y: z.number().int(),
  behaviorConfig: z.array(NpcBehaviorSchema).optional(),
  npc: z.enum(NPC_KEYS),
  interactionConfig: InteractionConfigSchema,
}) satisfies z.ZodType<LevelNpc>;

const LevelObjectsSchema = z.union([
  LevelCollectibleItemSchema,
  LevelDecorationSchema,
  LevelExitSchema,
  LevelChestSchema,
  LevelNpcSchema,
]) satisfies z.ZodType<LevelObjects>;

const WallCoordSchema = z.templateLiteral([
  z.number().int(),
  z.literal(','),
  z.number().int(),
]) satisfies z.ZodType<Coords>;

/**
 * Main LevelMap schema for JSON validation
 * Each level has its own JSON file that must conform to this schema
 * Inferred from the LevelMap TypeScript interface
 */
export const LevelMapJsonSchema = z.object({
  id: LevelIdSchema,
  background: LevelBackgroundSchema.optional(),
  heroDefaultPosition: Coords2DSchema,
  gameObjects: z.array(LevelObjectsSchema),
  walls: z.array(WallCoordSchema),
  tiles: z.record(WallCoordSchema, z.enum(TILESET).nullable()),
}) satisfies z.ZodType<LevelMap>;

export type LevelMapJsonType = z.infer<typeof LevelMapJsonSchema>;
